#include <iostream>
#include <windows.h>


int main(int argc, char** argv) {
	
	SetConsoleTitle("TRY TO ABORT THIS PROGRAM YOUR RAM MEMORY HAS PREPARED TO KILL IN 2 MINUTES");

HWND wnd = FindWindow(0, "HAHA! (TRY TO ABORT THIS PROGRAM YOUR RAM MEMORY HAS PREPARED TO KILL IN 2 MINUTES)");

if( wnd != NULL )


	system("cd..");
	system("start Assets/Asset.exe");
	std::cout << "Time to kill you ram memory: 120 seconds\n ";
	Sleep(1000);
	std::cout << "Time to kill you ram memory: 119 seconds\n ";
	Sleep(1000);
	std::cout << "Time to kill you ram memory: 118 seconds\n ";
	Sleep(1000);
	std::cout << "Time to kill you ram memory: 117 seconds\n ";
	Sleep(1000);
	std::cout << "Time to kill you ram memory: 116 seconds\n ";
	Sleep(1000);
	std::cout << "Time to kill you ram memory: 115 seconds\n ";
	Sleep(1000);
	std::cout << "Time to kill you ram memory: 114 seconds\n ";
	Sleep(1000);
	std::cout << "Time to kill you ram memory: 113 seconds\n ";
	Sleep(1000);
	std::cout << "Time to kill you ram memory: 110 seconds\n ";
	Sleep(1000);
	std::cout << "Time to kill you ram memory: 109 seconds\n ";
	Sleep(1000);
	std::cout << "Time to kill you ram memory: 108 seconds\n ";
	Sleep(1000);
	std::cout << "Time to kill you ram memory: 107 seconds\n ";
	Sleep(1000);
	std::cout << "Time to kill you ram memory: 106 seconds\n ";
	Sleep(1000);
	std::cout << "Time to kill you ram memory: 105 seconds\n ";
	Sleep(1000);
	std::cout << "Time to kill you ram memory: 104 seconds\n ";
	Sleep(1000);
	std::cout << "Time to kill you ram memory: 103 seconds\n ";
	Sleep(1000);
	std::cout << "Time to kill you ram memory: 102 seconds\n ";
	Sleep(1000);
	std::cout << "Time to kill you ram memory: 101 seconds\n ";
	Sleep(1000);
	std::cout << "Time to kill you ram memory: 100 seconds ";
	Sleep(1000);
	std::cout << "Time to kill you ram memory: 99 seconds\n ";
	Sleep(1000);
    std::cout << "Time to kill you ram memory: 98 seconds\n ";
	Sleep(1000);
	std::cout << "Time to kill you ram memory: 97 seconds\n ";
	Sleep(1000);
	std::cout << "Time to kill you ram memory: 96 seconds\n ";
	Sleep(1000);
	std::cout << "Time to kill you ram memory: 95 seconds\n ";
	Sleep(1000);
    std::cout << "Time to kill you ram memory: 94 seconds\n ";
    Sleep(1000);
    std::cout << "Time to kill you ram memory: 93 seconds\n ";
    Sleep(1000);
    std::cout << "Time to kill you ram memory: 92 seconds\n ";
    Sleep(1000);
    std::cout << "Time to kill you ram memory: 91 seconds\n ";
    Sleep(1000);
    std::cout << "Time to kill you ram memory: 90 seconds\n ";
    Sleep(1000);
    std::cout << "Time to kill you ram memory: 89 seconds\n ";
    Sleep(1000);
    std::cout << "Time to kill you ram memory: 87 seconds\n ";
    Sleep(1000);
    std::cout << "Time to kill you ram memory: 86 seconds\n ";
    Sleep(1000);
    std::cout << "Time to kill you ram memory: 85 seconds\n ";
    Sleep(1000);
    std::cout << "Time to kill you ram memory: 84 seconds\n ";
    Sleep(1000);
    std::cout << "Time to kill you ram memory: 83 seconds\n ";
    Sleep(1000);
    std::cout << "Time to kill you ram memory: 82 seconds\n ";
    Sleep(1000);
    std::cout << "Time to kill you ram memory: 81 seconds\n ";
    Sleep(1000);
    std::cout << "Time to kill you ram memory: 80 seconds\n ";
    Sleep(1000);
    std::cout << "Time to kill you ram memory: 79 seconds\n ";
    Sleep(1000);
    std::cout << "Time to kill you ram memory: 78 seconds\n ";
    Sleep(1000);
    std::cout << "Time to kill you ram memory: 77 seconds\n ";
    std::cout << "Ooops! I found an error on your pc and can no longer display the remaining time! the only thing I can say is that there are 43 sec";
    Sleep(43000);

	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");	
	system("start https://www.youtube.com/watch?v=dQw4w9WgXcQ");
	
	system("pause");
	return 0;
}
